services:
    frontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        environment:
            BACKEND_HOSTNAME: BACKEND_HOSTNAME_PLACEHOLDER
            HTTP_MODE: HTTP_MODE_PLACEHOLDER
        ports:
            - "8080:80"
        container_name: piped-frontend

    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        volumes:
            - ./config/config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        ports:
            - "8081:8080"
        container_name: piped-backend

    proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        ports:
            - "8082:8080"
        container_name: piped-proxy

    postgres:
        image: pgautoupgrade/pgautoupgrade:16-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: piped-postgres
