services:
    frontend:
        image: piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        env_file:
            - frontend.env
            - path: frontend.env.local
              required: false
        ports:
            - "8080:80"
        container_name: piped-frontend

    piped:
        image: piped:latest
        restart: unless-stopped
        volumes:
            - ./config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        ports:
            - "8081:8080"
        container_name: piped-backend

    proxy:
        image: piped-proxy:latest
        restart: unless-stopped
        ports:
            - "8082:8080"
        container_name: piped-proxy

    bg-helper:
        image: bg-helper-server:latest
        restart: unless-stopped
        container_name: piped-bg-helper

    postgres:
        image: pgautoupgrade/pgautoupgrade:16-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - postgres.env
            - path: postgres.env.local
              required: false
        container_name: piped-postgres
