services:
    frontend:
        image: piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        env_file:
            - frontend.env
            - path: frontend.env.local
              required: false
        container_name: piped-frontend
        networks:
            default:
                ipv4_address: 10.89.1.2

    piped:
        image: piped:latest
        restart: unless-stopped
        volumes:
            - ./config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        container_name: piped-backend
        networks:
            default:
                ipv4_address: 10.89.1.3

    proxy:
        image: piped-proxy:latest
        restart: unless-stopped
        container_name: piped-proxy
        networks:
            default:
                ipv4_address: 10.89.1.4

    bg-helper:
        image: bg-helper-server:latest
        restart: unless-stopped
        container_name: piped-bg-helper
        networks:
            default:
                ipv4_address: 10.89.1.5

    postgres:
        image: pgautoupgrade/pgautoupgrade:16-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - postgres.env
            - path: postgres.env.local
              required: false
        container_name: piped-postgres
        networks:
            default:
                ipv4_address: 10.89.1.6

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.89.1.0/24
          gateway: 10.89.1.1
